# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# create two lists and sum both of them together (results may not be what you expect)
l1 =[1,2,3]
l2 = [4,5,6]

print(f"summation of a regular python list: {l1 + l2}") 
# print(f"Difference of a regular pytohn list: {l1 -l2}")#list minus a list doesn't work

summation of a regular python list: [1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [2]:
def add(l1, l2):
    newL =[]
    for i in range(len(l1)):
        a = l1[i] + l2[i]
        newL.append(a)
    return newL

add([2,3,4],[1,5,2])

[3, 8, 6]

#### Importing

In [3]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

In [4]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [5]:
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


###### - np.zeros()

In [6]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [7]:
arr_ones = np.ones((3,3))
arr_ones
arr_ones_int = np.ones((3,3),int)
arr_ones_int

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [8]:
arr_range = np.arange(2,20,2)
arr_range

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

###### - Making Lists into NDArrays

In [9]:
list_1 = [5,6,7]
arr_list = np.array(list_1)
arr_list

array([5, 6, 7])

#### Performing Calculations on NDArrays

###### - Summation

In [10]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum




array([15, 30, 45, 60, 75])

###### - Difference

In [11]:
result_dif = arr_list1 + arr_list2
result_dif


array([15, 30, 45, 60, 75])

###### - Multiplication

In [12]:
result_mul = arr_list1 * arr_list2
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [13]:
result_div = arr_list2 / arr_list1
result_div

array([2., 2., 2., 2., 2.])

#### Modulo

In [14]:
result_mod = arr_list2 % arr_list1
result_mod

array([0, 0, 0, 0, 0], dtype=int32)

#### Floor Division

In [15]:
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2], dtype=int32)

#### Numpy Subsetting

In [26]:
# result3 <= 800
print(result_mul <= 800)
arr = np.array(result_mul <= 800)
print(arr.dtype)
print(result_mul[result_mul <= 800])

test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


[ True  True  True  True False]
bool
[ 50 200 450 800]
[]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [17]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
M
# print(M[1][1])

# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(f"NDArray structure:\n {ND_M}")



NDArray structure:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [18]:
print(f"Geting the middle element within the matrix: {ND_M[1,1]}")

Geting the middle element within the matrix: 4


#### Assigning Values in NDArrays

In [19]:
ND_M[1,1] = 9
ND_M 

array([[0, 1, 2],
       [3, 9, 5],
       [6, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [20]:
# usind the .dtype() method
nd_type = ND_M.dtype
nd_type

dtype('int32')

#### Altering NDArray Type

In [21]:
result_t = ND_M
print(f"befor :{result_t.dtype}")

changed = ND_M.astype(np.float)

print(f"type after change: {changed.dtype}")

befor :int32
type after change: float64


In [22]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
# changed.shape

#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [23]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
changed.shape

(3, 3)

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [24]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

changed.reshape((1,9)


SyntaxError: unexpected EOF while parsing (<ipython-input-24-283c7f20f14e>, line 9)

In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [ ]:
np.arange(0,16).reshape(4,4)

#### Complex Indexing & Assinging

In [ ]:
M = np.zeros((6,6))
print("resssting matrix")
print("Before:")
print(M)

#setevery first element in each row to 1
M[:,0] = 1
print("\n after assgining 1 to first column: ")
print(M)

#set all elements in axis 3 to 5 to be equal to the numbers
M[2:5,:] = 5
print("\n After assignin 5 to rows 2-5")
print(M)

#set them all to zeros
M = M * 0
print("\n set them all to zero")
print(M)

# set the second and third columns to 2
M[:,1:3] = 2
print("\n assgning 2 o the second and third rows")
print(M)

#Creatinga vector in numpy
v = np.arange(6)

#set the first row to that range of vectors numbers we just created
M[0, :] = v
print("\n assigning vector array v to the first axis in the matrix")
print(M)

In [ ]:
M *= 0
M[::2, ::2] = 2
M

#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [ ]:
#initialize a vector of range 6, then reset matrix to zero and run vector multipilcation on matrix
v = M[:,:] = 0
print(v)

#reset the Matrix to 0
M = M*v

print(M)

M.reshape((6,6))

In [ ]:
M = np.ones((6,6))
M

In [ ]:
v = np.arange(6)
M = M *v
M

#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [27]:
print(result_mul)
print('\n', np.where(result_mul < 800))

print('\n', result_mul[np.where(result_mul < 800)])
#transform data based on boolean mask == True
result_mul[np.where(result_mul < 800)] == 300
print('\n', result_mul)


[  50  200  450  800 1250]

 (array([0, 1, 2], dtype=int64),)

 [ 50 200 450]

 [  50  200  450  800 1250]



#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [ ]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

## Working With CSV's

#### Imports

In [ ]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [ ]:
# Creating Function to open and read CSV data
def open_csv(filename, d = ','):
    #define an empty list to store data 
    data = []
    
    with open(filename, encoding = 'utf-8')as mData:
        #use the csv reader method to create a python list
        info = csv.reader(mData,delimiter = d)
         
        #loop over info and append to data list 
        for row in info:
            data.append(row)
            
    return data

csv_data = open_csv('files/boston_marathon2017_edited.csv')

print(csv_data)

#### Loading a CSV's Data 

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



# instead of loading csv normally, let's load it into a numpy array to calculate results on

def load_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, skip_header=1,
                        usecols=np.arange(0,24), invalid_raise=False,
                        names=FIELDS, dtype=DATATYPES)
    return data

bs2017 = load_data('files/redsox_2017_hitting.txt')
# print(bs2017[:5])

names = bs2017['Name']
print(names)

#Find Total hits for 2017
total_hits = sum(bs2017['H'])
print(f'\n Total hits 2017: {total_hits}')

#find total home runs for the red sox 2017
total_hr = sum(bs2017['HR'])

print(f'\n Total home runs 2017: {total_hr }')

print(f'\n Hits per home runs 2017: {total_hits / total_hr }')

#### Summing the top 5 hitters for HR's

In [ ]:
# find the top 5 hr hitters
#step 1 : get al hr dat into a variable
#step 2 : get all player names
#setp 3 : create new list for new_names (empty to start)
#step 4 : decode the player names into a regular string
#step 5 : grab all data and place inside of a sipped list 
#step 6 : sort values based on HR data


#step 1:
all_hr = bs2017['HR']

#step 2:
all_names = bs2017['Name']

#step 3:
new_names = []

#step 4 
for name in range(len(all_names)):
    new_names.append(all_names[name].decode('utf-8'))
# print(new_names)

#step 5:
zipped_values = list(zip(new_names, all_hr))
print(zipped_values)

#step 6 
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse=True)
print(sorted_hr[:5])

# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>